
project_id = "mpmbduoffaldnkhrkxxp"

[functions.transform-story]
verify_jwt = true

[functions.regenerate-page]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-story-email]
verify_jwt = true
